app/models.py
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from datetime import datetime


from app import db, login

@login.user_loader
def load_user(id):
    return User.query.get(int(id))

#Table Creation
class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(60), unique=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(200))
    posts = db.relationship('Post', backref='author', lazy=True)

    def __repr__(self):
        return f'User: {self.username}'

    def commit(self):
        db.session.add(self)
        db.session.commit()

    def hash_password(self,password):
        return generate_password_hash(password)

    def check_password(self,password):
        return check_password_hash(self.password, password)
    
    # def get_id(self):
    #     return str(self.user_id)
    
class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True) 
    body = db.Column(db.String(250))
    timestamp = db.Column(db.DateTime, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

    def __repr__(self):
        return f'Post:\n{self.body}'
    
    def commit(self):
        db.session.add(self)
        db.session.commit()

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email

class RegisterForm(FlaskForm):
    username = StringField('username', validators=[DataRequired()])
    email = StringField('email', validators=[DataRequired(), Email()])
    password = PasswordField('password', validators=[DataRequired()])
    submit = SubmitField('Register')

class SignInForm(FlaskForm):
    username = StringField('username', validators=[DataRequired()])
    password = PasswordField('password', validators=[DataRequired()])
    submit = SubmitField('Signin')

class PostForm(FlaskForm):
    body = StringField('body', validators=[DataRequired()])
    submit = StringField('Post')

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_login import LoginManager

app = Flask(__name__)
app.config.from_object(Config)

db = SQLAlchemy(app)
migrate = Migrate(app, db)

login = LoginManager(app)

from app.blueprints.auth import bp as auth_bp
app.register_blueprint(auth_bp)
from app.blueprints.main import bp as main_bp
app.register_blueprint(main_bp)
from app.blueprints.social import bp as social_bp
app.register_blueprint(social_bp)

from app import models

app/blueprints/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.blueprints.main import routes

app/blueprints/main/routes.py
from flask import render_template

from . import bp

@bp.route('/')  
def home():
    matrix = {
        'instructors' : ('Sean', 'Dylan'),
        'students' : ['gian','hamed','gian','ben','chris','alec']

    }
    return render_template('index.jinja',title='Home',instructors = matrix['instructors'],students=matrix['students'])

@bp.route('/about')
def about():
    return render_template('about.jinja')

app/blueprints/social/__init__.py
from flask import Blueprint

bp = Blueprint('social', __name__, url_prefix='/social')

from . import routes

app/blueprints/social/routes.py
from flask import render_template
from . import bp
from flask_login import current_user

from app.models import Post
from app.forms import PostForm


@bp.route('/post', methods=['GET', 'POST'])
def post():
    form = PostForm()
    if form.validate_on_submit():
        p.user_id = current_user.user_id
        p = Post(body=form.body.data)
        p.commit()
        print(f'{p.author = } {p.author.posts[0]}')
    return render_template('post.jinja', form=form)

app/templates/about.jinja
{% extends 'base.jinja' %}

{% block content %}
    <h3>About Page</h3>
{% endblock %}

app/templates/base.jinja
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    
    <link rel="stylesheet" href="{{ url_for('static', filename='styles.css') }}">
    
    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Matrix Fakebook</title>
    {% endif %}
</head>

<body class="container">
    {% include "navbar.jinja" %}

    {% with messages = get_flashed_messages(with_categories=true) %}

        {% if messages %}
            <ul>
                {% for category, message in messages %}
                    <li class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}

  

    <h1>Matrix Fakebook</h1>

    {% block content %}{% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe"
        crossorigin="anonymous"></script>
</body>

</html>

app/templates/index.jinja
<!-- Jinga file type allows external logic like python to be written in html files -->
{% extends 'base.jinja' %}

{% block content %}
    <h3>Instructors</h3>
    <p>{{ instructors[0] }} {{ instructors[1] }}</p>

    <h3>Students</h3>
        {% for student in students %}
            <p>{{ student.title() }}</p>
        {% endfor %}

{% endblock %}

app/templates/navbar.jinja
<nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">Matrix Fakebook</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" aria-current="page" href="{{ url_for('main.home') }}">Home</a>
                    <a class="nav-link" href="{{ url_for('main.about') }}">About</a>
                    <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                    <a class="nav-link" href="{{ url_for('auth.signin') }}">Sign In</a>
                    <a class="nav-link" href="{{ url_for('social.post') }}">Post</a>
                </div>
            </div>
        </div>
    </nav>

app/templates/post.jinja
{% extends "base.jinja"%}

{% block content %}
     <form action="" method="post">
        <h3>Post</h3>
        {{ form.hidden_tag() }}
        <p>
            {{ form.body.label }}<br>
            {{ form.body(size=32) }}

            {% for error in form.body.errors %}
                <span class="error-msg"> {{ error }} </span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

app/templates/register.jinja
{% extends 'base.jinja' %}

{% block content %}
    <form action="" method="post">
        <h3>Register New Account</h3>
        {{ form.hidden_tag() }}
        <p>
            {{ form.username.label }}<br>
            {{ form.username(size=32) }}
        </p>
        <p>
            {{ form.email.label }}<br>
            {{ form.email(size=32) }}
            {% for error in form.email.errors %}
                <span class="error-msg"> {{ error }} </span>
            {% endfor %}
        </p>
        <p>
            {{ form.password.label }}<br>
            {{ form.password(size=32) }}
            {% for error in form.password.errors %}
                <span class="error-msg"> {{ error }} </span>
            {% endfor %}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
{% endblock %}

{# {% extends "base.jinja" %}

{% block content  %}
<form action="" method="post">
 <h2>Register</h2>
 {{ form.hidden_tag() }}
 <p>
    {{ form.username.label }}<br>
    {{ form.username(size=32) }}
 </p>
 <p>
    {{ form.email.label }}<br>
    {{ form.email(size=32) }}
    {% for error in form.email.errors %}
      <span class="error-msg">{{ error }}</span>
    {% endfor %}
 </p>
 <p>
    {{ form.password.label }}<br>
    {{ form.password(size=32) }}
    {% for error in form.password.errors %}
      <span class="error-msg">{{ error }}</span>
    {% endfor %}
 </p>
 <p>{{ form.submit() }}</p>
</form>
{% endblock  %} #}

app/templates/signin.jinja
{% extends 'base.jinja' %}

{% block content %}
    <h3>Sign Into Existing Account</h3>
        <form action="" method="post">
        <h3>Existing Username</h3>
            {{ form.hidden_tag() }}
            <p>
                {{ form.username.label }}<br>
                {{ form.username(size=32) }}
            </p>
            <p>
                {{ form.password.label }}<br>
                {{ form.password(size=32) }}
                {% for error in form.password.errors %}
                    <span class="error-msg"> {{ error }} </span>
                {% endfor %}
            </p>
            <p>{{ form.submit() }}</p>
        </form>
{% endblock %}